# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title: GU Mobile-RS
description: Somos um grupo destinado a compartilhar e promover encontros de desenvolvedores mobile no Rio Grande do Sul.
keywords: desenvolvimento móvel, mobile, rio grande do sul, grupo mobile do rio grande do sul, eventos, palestras
author:
  email : gumobilers@gmail.com
  github : https://github.com/gumobilers
  twitter: https://twitter.com/gumobilers